server:
  port: 8888
spring:
  profiles:
    active: default
  cloud:
    config:
      server:
        git:
          uri: https://github.com/onlinejavafullstacktraining/ConfigServer
          default-label: main
        encrypt:
          enabled: true
